### ISSUE TITLE
I get "KeyError: key not found" . 

### ISSUE THREAD

**Issue by ashwinputhige** [RailsApps/rails-stripe-membership-saas#143]
I am not an expert in rails, but here's the stack trace.

It occurs just after "run    bundle exec rake db:migrate from "."" and happens for all future "rake" commands.

    rake
    rake aborted!
    KeyError: key not found
    (erb):18:in `fetch'
    (erb):18:in `<main>'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/application.rb:391:in `secrets'
    /Users/ashwin/Documents/workspace/rails-starter/rails-stripe-membership-saas/config/initializers/devise.rb:15:in `block in <top (required)>'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/devise-3.5.1/lib/devise.rb:281:in `setup'
    /Users/ashwin/Documents/workspace/rails-starter/rails-stripe-membership-saas/config/initializers/devise.rb:3:in `<top (required)>'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/notifications.rb:166:in `instrument'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/engine.rb:651:in `load_config_initializer'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/engine.rb:615:in `each'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `each'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `tsort_each_child'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
    /Users/ashwin/Documents/workspace/rails-starter/rails-stripe-membership-saas/config/environment.rb:5:in `<top (required)>'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
    /Users/ashwin/Documents/workspace/rails-starter/rails-stripe-membership-saas/test/test_helper.rb:2:in `<top (required)>'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
    /Users/ashwin/Documents/workspace/rails-starter/rails-stripe-membership-saas/test/models/user_test.rb:1:in `<top (required)>'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:114:in `block (3 levels) in define'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:114:in `each'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:114:in `block (2 levels) in define'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:113:in `each'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:113:in `block in define'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:20:in `invoke_rake_task'
    /Users/ashwin/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.2.1/lib/rails/test_unit/testing.rake:8:in `block in <top (required)>'
    Tasks: TOP => test:run
    (See full trace by running task with --trace)

**Comment by DanielKehoe** [comment]
You need to set the MAILCHIMP_API_KEY and STRIPE_API_KEY values in either your Unix ENV variables or the *config/secrets.yml* file.

**Comment by ashwinputhige** [comment]
Hey Daniel, Thanks for the quick reply but unfortunately that did not fix it :( ..

**Comment by rsgrafx** [comment]
Open terminal and at the command line $> source ~/.bash_profile or ~/.profile.  at the command prompt and type `echo $MAILCHIMP_API_KEY  if you see the key you specified. restart rails.

**Comment by ashwinputhige** [comment]
I can see the key but the error still exists .

**Comment by rsgrafx** [comment]
I'm getting the same error cant find the issue myself .. this is after doing a search and commenting out all blocks of code where I see Rails.application.secrets.whatever_key , in the initializers - in the user model in the secrets.yml. Just to get the first initial migration going.

$> `rake db:migrate`

rake aborted!

KeyError: key not found: "MAILCHIMP_API_KEY"
(erb):20:in `fetch'
(erb):20:in <main>

**Comment by DanielKehoe** [comment]
In your *config/secrets.yml* file, replace the following:
```
  mailchimp_api_key: <%= ENV.fetch("MAILCHIMP_API_KEY") %>
  mailchimp_list_id: <%= ENV.fetch("MAILCHIMP_LIST_ID") %>
  stripe_api_key: <%= ENV.fetch("STRIPE_API_KEY") %>
  stripe_publishable_key: <%= ENV.fetch("STRIPE_PUBLISHABLE_KEY") %>
```
with:
```
  mailchimp_api_key: yourkey
  mailchimp_list_id: yourlistid
  stripe_api_key: yourkey
  stripe_publishable_key: yourkey
```

**Comment by ashwinputhige** [comment]
@rsgrafx Did you manage to fix this issue?
@DanielKehoe  Can we 'open' this issue?

**Comment by DanielKehoe** [comment]
I've reopened the issue as requested. Is there anyone who has not been able to resolve the issue by setting the Unix ENV variables or hardcoding the vales in the *config/secrets.yml* file?

**Comment by nikolay12** [comment]
I haven't been able, either. I changed quite a few things and made it to work. Will commit to the fork and than try to diff to find out what is it that made it work

**Comment by DanielKehoe** [comment]
The only purpose of the ```fetch`` method is to force an error if the API keys are not available in the Unix ENV variables when the application is started. This lets the developer know that the API key is not available and avoids more mysterious errors later. You can remove the ```fetch`` method from the *config/secrets.yml* file and the application will run without the initial error. But it will fail later if the API key is not available.

See https://github.com/RailsApps/rails-stripe-membership-saas/commit/3fce46406f9786109cf3bcd536c67e71fe1caae4

**Comment by ashwinputhige** [comment]
@DanielKehoe  More info : I get this error while running the composer command `$ rails new rails-stripe-membership-saas -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb`

 The errors don't go away even after adding the API keys in the environment variables.

**Comment by DanielKehoe** [comment]
@ashwinputhige Could you clarify please, do you get the I get "KeyError: key not found" when the Rails Composer script is running (causing a failure before an app is created)? Or do you build an app using Rails Composer successfully, and then get the error when you launch the app with ```rails server```?

**Comment by ashwinputhige** [comment]
I get it when the rails composer script is running before the app is created. It happens at the command `bundle exec rake db:command (I believe its db:migrate)`. I can retry if that is important.

**Comment by DanielKehoe** [comment]
Thank you @ashwinputhige, that is helpful.

**Comment by DanielKehoe** [comment]
I've released a new version of Rails Composer that removes the ```fetch``` method from the *config/secrets.yml* file. @ashwinputhige please give it a try and let me know if the issue is resolved.

**Comment by kathyonu** [comment]
@ashwinputhige , please see the tests you can put in place for this, the [spec/stripe/stripe_config_spec.rb](https://github.com/kathyonu/rails-stripe-membership-saas/blob/truenorth/spec/stripe/stripe_config_spec.rb) file. for more info please see Issue #149 which resolves the lack of tests on the membership app

**Comment by kathyonu** [comment]
@ashwinputhige @nikolay12 @rsgrafx : Please see [PR Testsformaster #150](https://github.com/RailsApps/rails-stripe-membership-saas/pull/150) .  I invite you to pull this branch into your working app, and take it for a spin. You will see it has tests that resolve Issue #143 . If you can help resolve the four pending tests, that would be grand, thank you.

**Comment by ashwinputhige** [comment]
@kathyonu Sorry, I am not using this application and so I will not be able to run your tests. Please feel free to close the issue if required.

**Comment by panzhuli** [comment]
I'm not using Rails composer and simply cloned the repo and am having the same issue. I entered my keys into my secrets.yml file (i.e. no ENV vars) so suspect the changes proposed above won't work. I have the following results:

> rails s
=> Booting WEBrick
=> Rails 4.2.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
(erb):39:in `fetch': key not found: "MAILCHIMP_API_KEY" (KeyError)
    from (erb):39:in `<main>'
    from /Users/panzhuli/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval'
    from /Users/panzhuli/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `result'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/application.rb:391:in `secrets'
    from /Users/panzhuli/WebProjects/pname/config/environments/development.rb:30:in `block in <top (required)>'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/railtie.rb:210:in `instance_eval'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/railtie.rb:210:in `configure'
    from /Users/panzhuli/WebProjects/pname/config/environments/development.rb:1:in `<top (required)>'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/engine.rb:597:in `each'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/engine.rb:597:in `block in <class:Engine>'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/panzhuli/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
    from /Users/panzhuli/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    from /Users/panzhuli/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
    from /Users/panzhuli/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
    from /Users/panzhuli/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `each'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `tsort_each_child'
    from /Users/panzhuli/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `call'
    from /Users/panzhuli/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
    from /Users/panzhuli/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
    from /Users/panzhuli/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
    from /Users/panzhuli/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
    from /Users/panzhuli/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
    from /Users/panzhuli/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
    from /Users/panzhuli/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
    from /Users/panzhuli/WebProjects/pname/config/environment.rb:5:in `<top (required)>'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
    from /Users/panzhuli/WebProjects/pname/config.ru:3:in `block in <main>'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
    from /Users/panzhuli/WebProjects/pname/config.ru:in `new'
    from /Users/panzhuli/WebProjects/pname/config.ru:in `<main>'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/server.rb:61:in `app'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/server.rb:139:in `log_to_stdout'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/server.rb:78:in `start'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
    from /Users/panzhuli/WebProjects/pname/bin/rails:8:in `require'
    from /Users/panzhuli/WebProjects/pname/bin/rails:8:in `<top (required)>'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/spring-1.3.4/lib/spring/client/rails.rb:28:in `load'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/spring-1.3.4/lib/spring/client/rails.rb:28:in `call'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/spring-1.3.4/lib/spring/client/command.rb:7:in `call'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/spring-1.3.4/lib/spring/client.rb:26:in `run'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/spring-1.3.4/bin/spring:48:in `<top (required)>'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/spring-1.3.4/lib/spring/binstub.rb:11:in `load'
    from /Users/panzhuli/.rvm/gems/ruby-2.2.2/gems/spring-1.3.4/lib/spring/binstub.rb:11:in `<top (required)>'
    from /Users/panzhuli/WebProjects/pname/bin/spring:13:in `require'
    from /Users/panzhuli/WebProjects/pname/bin/spring:13:in `<top (required)>'
    from bin/rails:3:in `load'
    from bin/rails:3:in `<main>'

**Comment by nikolay12** [comment]
I just git cloned the repository - the problem still persists. I cancelled my Railsapp subscription - sorry Daniel, it just does not make sense to continue paying for something that is so brittle.

**Comment by kathyonu** [comment]
@nikolay12 @ashwinputhige @rsgrafx  @DanielKehoe  Greetings .. I have changed my mind, ashwinputhige, and nikolay12 I ask you to change yours too .. If you will look at Issue #152, specifically the posts i made there yesterday ..you will find a resource that really is priceless in these matters of setting the enviroment variables.  So that you know, I have an in production rails-stripe-membership-saas running sweet as can be, and I have gone through the exact same issues you are facing and I can easily help resolve them for you .. and others you may run into.  Please re-signup with RailsApps if need be and accept this offer of help and you will have a high power fully-tested app at your fingertips .. the tests are arriving as referred to in Issue #152 and more to come. We are also going to be adding capabilities after what exists is fully tested.

**Comment by ysksn** [comment]
try this :)
`bin/spring stop`

**Comment by AnythingLinux** [comment]
![screenshot from 2019-01-31 19-33-33](https://user-images.githubusercontent.com/1058663/52057415-1f77b280-258f-11e9-8724-cf83a6cbdd9f.png)
same problem using ubuntu 16

**Comment by aliwaqar981** [comment]
Getting same error. Any solution?

**Comment by pmutale** [comment]
Here too! This was working until I updated rails to 6.1
